# PYTHON NUMBERS

# PYTHON NUMBERS
# THERE ARE THREE NUMERIC TYPES IN PYTHON:
# INT
# FLOAT
# COMPLEX
# VARIABLES OF NUMERIC TYPES ARE CREATED WHEN YOU ASSIGN A VALUE TO THEM:
# EXAMPLE
x = 1 # INT
y = 2.8 # FLOAT
z = 1j # COMPLEX

# TO VERIFY THE TYPE OF ANY OBJECT IN PYTHON, USE THE TYPE() FUNCTION:
# EXAMPLE
print(type(x))
print(type(y))
print(type(z))

# INT
# INT, OR INTEGER, IS A WHOLE NUMBER, POSITIVE OR NEGATIVE, WITHOUT DECIMALS, OF UNLIMITED LENGTH.
# EXAMPLE
x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

# FLOAT
# FLOAT, OR "FLOATING POINT NUMBER" IS A NUMBER, POSITIVE OR NEGATIVE, CONTAINING ONE OR MORE DECIMALS.
# EXAMPLE
x = 1.10
y = 1.0
z = -35.59

print(type(x))
print(type(y))
print(type(z))

# FLOAT CAN ALSO BE SCIENTIFIC NUMBERS WITH AN "E" TO INDICATE THE POWER OF 10.
# EXAMPLE
x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))

# COMPLEX
# COMPLEX NUMBERS ARE WRITTEN WITH A "J" AS THE IMAGINARY PART:
# EXAMPLE
x = 3+5j
y = 5j
z = -5j

print(type(x))
print(type(y))
print(type(z))

# TYPE CONVERSION
# YOU CAN CONVERT FROM ONE TYPE TO ANOTHER WITH THE INT(), FLOAT(), AND COMPLEX() METHODS:
# EXAMPLE
x = 1 # INT
y = 2.8 # FLOAT
z = 1j # COMPLEX

# CONVERT FROM INT TO FLOAT:
a = float(x)

# CONVERT FROM FLOAT TO INT:
b = int(y)

# CONVERT FROM INT TO COMPLEX:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))
# NOTE: YOU CANNOT CONVERT COMPLEX NUMBERS INTO ANOTHER NUMBER TYPE.

# RANDOM NUMBER
""" PYTHON DOES NOT HAVE A RANDOM() FUNCTION TO MAKE A RANDOM NUMBER, BUT PYTHON HAS A BUILT-IN MODULE CALLED 
RANDOM THAT CAN BE USED TO MAKE RANDOM NUMBERS: """
# EXAMPLE
import random

print(random.randrange(1, 10))