# PYTHON SCOPES

# A VARIABLE IS ONLY AVAILABLE FROM INSIDE THE REGION IT IS CREATED. THIS IS CALLED SCOPE.

# LOCAL SCOPE
# A VARIABLE CREATED INSIDE A FUNCTION BELONGS TO THE LOCAL SCOPE OF THAT FUNCTION, AND CAN
# ONLY BE USED INSIDE THAT FUNCTION.

# EXAMPLE
# A VARIABLE CREATED INSIDE A FUNCTION IS AVAILABLE INSIDE THAT FUNCTION:
def myfunc():
    x = 300
    print(x)


myfunc()

# FUNCTION INSIDE FUNCTION
# AS EXPLAINED IN THE EXAMPLE ABOVE, THE VARIABLE X IS NOT AVAILABLE OUTSIDE THE FUNCTION,
# BUT IT IS AVAILABLE FOR ANY FUNCTION INSIDE THE FUNCTION:

# EXAMPLE
# THE LOCAL VARIABLE CAN BE ACCESSED FROM A FUNCTION WITHIN THE FUNCTION:


def myfunc():
    x = 300

    def myinnerfunc():
        print(x)

    myinnerfunc()


myfunc()

# GLOBAL SCOPE
# A VARIABLE CREATED IN THE MAIN BODY OF THE PYTHON CODE IS A GLOBAL VARIABLE AND BELONGS TO
# THE GLOBAL SCOPE.
# GLOBAL VARIABLES ARE AVAILABLE FROM WITHIN ANY SCOPE, GLOBAL AND LOCAL.

# EXAMPLE
# A VARIABLE CREATED OUTSIDE OF A FUNCTION IS GLOBAL AND CAN BE USED BY ANYONE:
x = 300


def myfunc():
    print(x)


myfunc()
print(x)

# NAMING VARIABLES
# IF YOU OPERATE WITH THE SAME VARIABLE NAME INSIDE AND OUTSIDE OF A FUNCTION, PYTHON WILL
# TREAT THEM AS TWO SEPARATE VARIABLES, ONE AVAILABLE IN THE GLOBAL SCOPE (OUTSIDE THE
# FUNCTION) AND ONE AVAILABLE IN THE LOCAL SCOPE (INSIDE THE FUNCTION):

# EXAMPLE
# THE FUNCTION WILL PRINT THE LOCAL X, AND THEN THE CODE WILL PRINT THE GLOBAL X:
x = 300


def myfunc():
    x = 200
    print(x)


myfunc()
print(x)

# GLOBAL KEYWORD
# IF YOU NEED TO CREATE A GLOBAL VARIABLE, BUT ARE STUCK IN THE LOCAL SCOPE, YOU CAN USE THE
# GLOBAL KEYWORD.
# THE GLOBAL KEYWORD MAKES THE VARIABLE GLOBAL.

# EXAMPLE
# IF YOU USE THE GLOBAL KEYWORD, THE VARIABLE BELONGS TO THE GLOBAL SCOPE:


def myfunc():
    global x
    x = 300


myfunc()
print(x)

# ALSO, USE THE GLOBAL KEYWORD IF YOU WANT TO MAKE A CHANGE TO A GLOBAL VARIABLE INSIDE A
# FUNCTION.

# EXAMPLE
# TO CHANGE THE VALUE OF A GLOBAL VARIABLE INSIDE A FUNCTION, REFER TO THE VARIABLE BY USING
# THE GLOBAL KEYWORD:
x = 300


def myfunc():
    global x
    x = 200


myfunc()

print(x)
