# PYTHON - LOOP TUPLES

# LOOP THROUGH A TUPLE
# YOU CAN LOOP THROUGH THE TUPLE ITEMS BY USING A FOR LOOP
# EXAMPLE
# ITERATE THROUGH THE ITEMS AND PRINT THE VALUES
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
    print(x)

# LOOP THROUGH THE INDEX NUMBERS
# YOU CAN ALSO LOOP THROUGH THE TUPLE ITEMS BY REFERRING TO THEIR INDEX NUMBER
# USE THE RANGE() AND LEN() FUNCTIONS TO CREATE A SUITABLE ITERABLE
# EXAMPLE
# PRINT ALL ITEMS BY REFERRING TO THEIR INDEX NUMBER
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
    print(thistuple[i])

# USING A WHILE LOOP
# YOU CAN LOOP THROUGH THE LIST ITEMS BY USING A WHILE LOOP
# USE THE LEN() FUNCTION TO DETERMINE THE LENGTH OF THE TUPLE, THEN START AT 0 AND LOOP
# YOUR WAY THROUGH THE TUPLE ITEMS BY REFERENCING THEIR INDEX NUMBER
# REMEMBER TO INCREASE THE INDEX BY 1 AFTER EACH ITERATION
# EXAMPLE
# PRINT ALL ITEMS, USING A WHILE LOOP TO GO THROUGH ALL THE INDEX NUMBERS
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
    print(thistuple[i])
    i = i + 1
