# PYTHON - ESCAPE CHARACTERS

# ESCAPE CHARACTER
# TO INSERT CHARACTERS THAT ARE ILLEGAL IN A STRING, USE AN ESCAPE CHARACTER.
# AN ESCAPE CHARACTER IS A BACKSLASH \ FOLLOWED BY THE CHARACTER YOU WANT TO INSERT.
# AN EXAMPLE OF AN ILLEGAL CHARACTER IS A DOUBLE QUOTE INSIDE A STRING THAT IS SURROUNDED BY DOUBLE QUOTES:
# FIX THE ERROR BY USING AN ESCAPE CHARACTER:
txt = "We are the so-called \"Vikings\" from the north."

# OTHER ESCAPE CHARACTERS USED IN PYTHON:
# \'    Single Quote
# \\    Backslash
# \n    New Line
# \r    Carriage Return
# \t    Tab
# \b    Backspace
# \f    Form Feed
# \ooo  Octal Value
# \xhh  Hex Value