# PYTHON FILE WRITE

# WRITE TO AN EXISTING FILE
# TO WRITE TO AN EXISTING FILE, YOU MUST ADD A PARAMETER TO THE OPEN() FUNCTION:
# "A" - APPEND - WILL APPEND TO THE END OF THE FILE
# "W" - WRITE - WILL OVERWRITE ANY EXISTING CONTENT

# EXAMPLE
# OPEN THE FILE "DEMOFILE2.TXT" AND APPEND CONTENTS TO THE FILE:
f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

# OPEN AND READ THE FILE AFTER THE APPEND:
f = open("demofile2.txt", "r")
print(f.read())

# EXAMPLE
# OPEN THE FILE "DEMOFILE3.TXT" AND OVERWRITE THE CONTENTS:
f = open("demofile3.txt", "w")
f.write("Woops! I have deleted the content!")
f.close()

# OPEN AND READ THE FILE AFTER THE WRITE:
f = open("demofile3.txt", "r")
print(f.read())

# NOTE: THE "W" METHOD WILL OVERWRITE THE ENTIRE FILE.

# CREATE A NEW FILE
# TO CREATE A NEW FILE IN PYTHON, USE THE OPEN() METHOD, WITH ONE OF THE FOLLOWING
# PARAMETERS:
# "X" - CREATE - WILL CREATE A FILE, RETURNS AN ERROR IF THE FILE EXISTS
# "A" - APPEND - WILL CREATE A FILE IF THE SPECIFIED FILE DOES NOT EXIST
# "W" - WRITE - WILL CREATE A FILE IF THE SPECIFIED FILE DOES NOT EXIST

# EXAMPLE
# CREATE A FILE CALLED "MYFILE.TXT":
f = open("myfile.txt", "x")

# RESULT: A NEW EMPTY FILE IS CREATED!

# EXAMPLE
# CREATE A NEW FILE IF IT DOES NOT EXIST:
f = open("myfile.txt", "w")