# CREATE A MODULE
# TO CREATE A MODULE JUST SAVE THE CODE YOU WANT IN A FILE WITH THE FILE EXTENSION .PY:

# EXAMPLE
# SAVE THIS CODE IN A FILE NAMED MYMODULE.PY
def greeting(name):
    print("Hello, " + name)

# VARIABLES IN MODULES
# THE MODULE CAN CONTAIN FUNCTIONS, AS ALREADY DESCRIBED, BUT ALSO VARIABLES OF ALL TYPES
# (ARRAYS, DICTIONARIES, OBJECTS ETC):

# EXAMPLE
# SAVE THIS CODE IN THE FILE MYMODULE.PY
person1 = {
    "name": "John",
    "age": 36,
    "country": "Norway"
}

