# PYTHON WHILE LOOPS

# PYTHON LOOPS
# PYTHON HAS TWO PRIMITIVE LOOP COMMANDS:
# WHILE LOOPS
# FOR LOOPS

# THE WHILE LOOP
# WITH THE WHILE LOOP WE CAN EXECUTE A SET OF STATEMENTS AS LONG AS A CONDITION IS TRUE.

# EXAMPLE
# PRINT I AS LONG AS I IS LESS THAN 6:
i = 1
while i < 6:
    print(i)
    i += 1

# NOTE: REMEMBER TO INCREMENT I, OR ELSE THE LOOP WILL CONTINUE FOREVER.

# THE WHILE LOOP REQUIRES RELEVANT VARIABLES TO BE READY, IN THIS EXAMPLE WE NEED TO DEFINE AN INDEX VARIABLE, I,
# WHICH WE SET TO 1.

# THE BREAK STATEMENT
# WITH THE BREAK STATEMENT WE CAN STOP THE LOOP EVEN IF THE WHILE CONDITION IS TRUE:

# EXAMPLE
# EXIT THE LOOP WHEN I IS 3:
i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

# THE CONTINUE STATEMENT
# WITH THE CONTINUE STATEMENT WE CAN STOP THE CURRENT ITERATION, AND CONTINUE WITH THE NEXT:

# EXAMPLE
# CONTINUE TO THE NEXT ITERATION IF I IS 3:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

# THE ELSE STATEMENT
# WITH THE ELSE STATEMENT WE CAN RUN A BLOCK OF CODE ONCE WHEN THE CONDITION NO LONGER IS TRUE:

# EXAMPLE
# PRINT A MESSAGE ONCE THE CONDITION IS FALSE:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")
