# PYTHON VARIABLES

# VARIABLES
# VARIABLES ARE CONTAINERS FOR STORING DATA VALUES

# CREATING VARIABLES
# PYTHON HAS NO COMMAND FOR DECLARING A VARIABLE
# A VARIABLE IS CREATED THE MOMENT YOU FIRST ASSIGN A VALUE TO IT
x = 5
y = "John"
print(x)
print(y)

""" VARIABLES DO NOT NEED TO BE DECLARED WITH ANY PARTICULAR TYPE, AND CAN EVEN CHANGE TYPE
AFTER THEY HAVE BEEN SET """
x = 4       # x IS OF TYPE INT
x = "Sally" # x IS NOW OF TYPE STR
print(x)

# CASTING
# IF YOU WANT TO SPECIFY THE DATA TYPE OF A VARIABLE, THIS CAN BE DONE WITH CASTING
x = str(3)      # x WILL BE '3'
y = int(3)      # y WILL BE 3
z = float(3)    # z WILL BE 3.0

# GET THE TYPE
# YOU CAN GET THE DATA TYPE OF A VARIABLE WITH THE TYPE() FUNCTION
x = 5
y = "John"
print(type(x))
print(type(y))

# SINGLE OR DOUBLE QUOTES
# STRING VARIABLES CAN BE DECLARED EITHER BY USING SINGLE OR DOUBLE QUOTES
x = "John"
# IS THE SAME AS
x = 'John'

# CASE SENSITIVE
# VARIABLE NAMES ARE CASE-SENSITIVE
# EXAMPLE:
a = 4
A = "Sally"
# A WILL NOT OVERWRITE a