# PYTHON USER INPUT

# USER INPUT
# PYTHON ALLOWS FOR USER INPUT.
# THAT MEANS WE ARE ABLE TO ASK THE USER FOR INPUT.
# THE METHOD IS A BIT DIFFERENT IN PYTHON 3.6 THAN PYTHON 2.7.
# PYTHON 3.6 USES THE INPUT() METHOD.
# PYTHON 2.7 USES THE RAW_INPUT() METHOD.
# THE FOLLOWING EXAMPLE ASKS FOR THE USER'S NAME, THEN, BY USING THE INPUT() METHOD, THE
# PROGRAM PRINTS THE NAME TO THE SCREEN:

# EXAMPLE
username = input("Enter username:")
print("Username is: " + username)

# PYTHON STOPS EXECUTING WHEN IT COMES TO THE INPUT() FUNCTION AND CONTINUES WHEN THE USER
# HAS GIVEN SOME INPUT.