# OUTPUT VARIABLES

# THE PYTHON PRINT() FUNCTION IS OFTEN USED TO OUTPUT VARIABLES
x = "awesome"
print("Python is " + x)

# IN THE PRINT() FUNCTION, YOU OUTPUT MULTIPLE VARIABLES, SEPARATED BY A COMMA
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

# YOU CAN ALSO USE THE + CHARACTER TO ADD A VARIABLE TO ANOTHER VARIABLE
print(x + y + z)

# FOR NUMBERS, THE + CHARACTER WORKS AS A MATHEMATICAL OPERATOR
x = 5
y = 10
print(x + y)

""" IN THE PRINT() FUNCTION, WHEN YOU TRY TO COMBINE A STRING AND A NUMBER WITH THE +
OPERATOR, PYTHON WILL GIVE YOU AN ERROR """
x = 5
y = "John"
# print(x + y)

""" THE BEST WAY TO OUTPUT MULTIPLE VARIABLES WITH THE PRINT() FUNCTION IS TO SEPARATE THEM WITH COMMAS, 
WHICH EVEN SUPPORTS DIFFERENT DATA TYPES """
x = "awesome"
print(x, y)