# PYTHON - MODIFY STRINGS
# PYTHON HAS A SET OF BUILT-IN METHODS THAT YOU CAN USE ON STRINGS.

# UPPER CASE
# THE UPPER() METHOD RETURNS THE STRING IN UPPER CASE:
a = "Hello, World!"
print(a.upper())

# LOWER CASE
# THE LOWER() METHOD RETURNS THE STRING IN LOWER CASE:
a = "Hello, World!"
print(a.lower())

# REMOVE WHITESPACE
# WHITESPACE IS THE SPACE BEFORE AND/OR AFTER THE ACTUAL TEXT, AND VERY OFTEN YOU WANT TO REMOVE THIS SPACE.
# THE STRIP() METHOD REMOVES ANY WHITESPACE FROM THE BEGINNING OR THE END:
a = " Hello, World! "
print(a.strip())  # returns "Hello, World!"

# REPLACE STRING
# THE REPLACE() METHOD REPLACES A STRING WITH ANOTHER STRING:
a = "Hello, World!"
print(a.replace("H", "J"))

# SPLIT STRING
# THE SPLIT() METHOD SPLITS THE STRING INTO SUBSTRINGS IF IT FINDS INSTANCES OF THE SEPARATOR:
a = "Hello, World!"
print(a.split(","))  # returns ['Hello', ' World!']