# PYTHON FILE OPEN

# FILE HANDLING IS AN IMPORTANT PART OF ANY WEB APPLICATION.
# PYTHON HAS SEVERAL FUNCTIONS FOR CREATING, READING, UPDATING, AND DELETING FILES.

# FILE HANDLING
# THE KEY FUNCTION FOR WORKING WITH FILES IN PYTHON IS THE OPEN() FUNCTION.
# THE OPEN() FUNCTION TAKES TWO PARAMETERS; FILENAME, AND MODE.
# THERE ARE FOUR DIFFERENT METHODS (MODES) FOR OPENING A FILE:
# "R" - READ - DEFAULT VALUE. OPENS A FILE FOR READING, ERROR IF THE FILE DOES NOT EXIST
# "A" - APPEND - OPENS A FILE FOR APPENDING, CREATES THE FILE IF IT DOES NOT EXIST
# "W" - WRITE - OPENS A FILE FOR WRITING, CREATES THE FILE IF IT DOES NOT EXIST
# "X" - CREATE - CREATES THE SPECIFIED FILE, RETURNS AN ERROR IF THE FILE EXISTS    

# IN ADDITION YOU CAN SPECIFY IF THE FILE SHOULD BE HANDLED AS BINARY OR TEXT MODE

# "T" - TEXT - DEFAULT VALUE. TEXT MODE
# "B" - BINARY - BINARY MODE (E.G. IMAGES)

# SYNTAX
# TO OPEN A FILE FOR READING IT IS ENOUGH TO SPECIFY THE NAME OF THE FILE:
# F = OPEN("DEMO.TXT")

# THE CODE ABOVE IS THE SAME AS:
# F = OPEN("DEMO.TXT", "RT")

# BECAUSE "R" FOR READ, AND "T" FOR TEXT ARE THE DEFAULT VALUES, YOU DO NOT NEED TO SPECIFY
# THEM.

# NOTE: MAKE SURE THE FILE EXISTS, OR ELSE YOU WILL GET AN ERROR.