# PYTHON MATH

# PYTHOM HAS A SET OF BUILT-IN MATH FUNCTIONS, INCLUDING AN EXTENSIVE MATH MODULE, THAT
# ALLOWS YOU TO PERFORM MATHEMATICAL TASKS ON NUMBERS.

# BUILT IN MATH FUNCTIONS
# THE MIN AND MAX FUNCTIONS CAN BE USED TO FIND THE LOWEST OR HIGHEST VALUE IN AN ITERABLE:

# EXAMPLE
import math
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

# THE ABS() FUNCTION RETURNS THE ABSOLUTE (POSITIVE) VALUE OF THE SPECIFIED NUMBER:

# EXAMPLE
x = abs(-7.25)
print(x)

# THE POW(X, Y) FUNCTION RETURNS THE VALUE OF X TO THE POWER OF Y (XY).

# EXAMPLE
# RETURN THE VALUE OF 4 TO THE POWER OF 3 (SAME AS 4 * 4 * 4):
x = pow(4, 3)
print(x)

# THE MATH MODULE
# PYTHON HAS ALSO A BUILT-IN MODULE CALLED MATH, WHICH EXTENDS THE LIST OF MATHEMATICAL
# FUNCTIONS.
# TO USE IT, YOU MUST IMPORT THE MATH MODULE:

# WHEN YOU HAVE IMPORTED THE MATH MODULE, YOU CAN START USING METHODS AND CONSTANTS OF THE
# MODULE.
# THE MATH.SQRT() METHOD FOR EXAMPLE, RETURNS THE SQUARE ROOT OF A NUMBER:

# EXAMPLE
x = math.sqrt(64)
print(x)

# THE MATH.CEIL() METHOD ROUNDS A NUMBER UP TO THE NEAREST INTEGER, AND THE MATH.FLOOR()
# METHOD ROUNDS A NUMBER DOWN TO THE NEAREST INTEGER, AND RETURNS THE RESULT:

# EXAMPLE
x = math.ceil(1.4)
y = math.floor(1.4)

print(x)
print(y)

# THE MATH.PI CONSTANT, RETURNS THE VALUE OF PI (3.14...):

# EXAMPLE
x = math.pi
print(x)
