# PYTHON - CHANGE LIST ITEMS

# CHANGE ITEM VALUE
# TO CHANGE THE VALUE OF A SPECIFIC ITEM, REFER TO THE INDEX NUMBER:
# CHANGE THE SECOND ITEM:
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

# CHANGE A RANGE OF ITEM VALUES
""" TO CHANGE THE VALUE OF ITEMS WITHIN A SPECIFIC RANGE, DEFINE A LIST WITH THE NEW VALUES, AND REFER TO THE 
RANGE OF INDEX NUMBERS WHERE YOU WANT TO INSERT THE NEW VALUES: """
# CHANGE THE VALUES "BANANA" AND "CHERRY" WITH THE VALUES "BLACKCURRANT" AND "WATERMELON":
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

""" IF YOU INSERT MORE ITEMS THAN YOU REPLACE, THE NEW ITEMS WILL BE INSERTED WHERE YOU SPECIFIED, AND THE 
REMAINING ITEMS WILL MOVE ACCORDINGLY: """
# CHANGE THE SECOND VALUE BY REPLACING IT WITH TWO NEW VALUES:
thislist = ["apple", "banana", "cherry"]
thislist[1:2] = ["blackcurrant", "watermelon"]
print(thislist)
""" NOTE: THE LENGTH OF THE LIST WILL CHANGE WHEN THE NUMBER OF ITEMS INSERTED DOES NOT MATCH THE NUMBER OF 
ITEMS REPLACED """

""" IF YOU INSERT LESS ITEMS THAN YOU REPLACE, THE NEW ITEMS WILL BE INSERTED WHERE YOU SPECIFIED, AND THE
REMAINING ITEMS WILL MOVE ACCORDINGLY: """
# CHANGE THE SECOND AND THIRD VALUE BY REPLACING IT WITH ONE VALUE:
thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon"]
print(thislist)

# INSERT ITEMS
# TO INSERT A NEW LIST ITEM, WITHOUT REPLACING ANY OF THE EXISTING VALUES, WE CAN USE THE INSERT() METHOD.
# THE INSERT() METHOD INSERTS AN ITEM AT THE SPECIFIED INDEX:
# INSERT "WATERMELON" AS THE THIRD ITEM:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)
# NOTE: AS A RESULT OF THE EXAMPLE ABOVE, THE LIST WILL NOW CONTAIN 4 ITEMS.