# PYTHON CASTING
# SPECIFY A VARIABLE TYPE
""" THERE MAY BE TIMES WHEN YOU WANT TO SPECIFY A TYPE ON TO A VARIABLE. THIS CAN BE DONE WITH CASTING. PYTHON IS AN 
OBJECT-ORIENTED LANGUAGE, AND AS SUCH IT USES CLASSES TO DEFINE DATA TYPES, INCLUDING ITS PRIMITIVE TYPES. """
# CASTING IN PYTHON IS THEREFORE DONE USING CONSTRUCTOR FUNCTIONS:
# EXAMPLE
""" INT() - CONSTUCTS AN INTEGER NUMBER FROM AN INTEGER LITERAL, A FLOAT LITERAL (BY REMOVING ALL DECIMALS), OR A STRING
LITERAL (PROVIDED THE STRING REPRESENTS A WHOLE NUMBER) """
""" FLOAT() - CONSTRUCTS A FLOAT NUMBER FROM AN INTEGER LITERAL, A FLOAT LITERAL OR A STRING LITERAL (PROVIDED THE STRING
REPRESENTS A FLOAT OR AN INTEGER) """
""" STR() - CONSTRUCTS A STRING FROM A WIDE VARIETY OF DATA TYPES, INCLUDING STRINGS, INTEGER LITERALS AND FLOAT LITERALS """

# EXAMPLE
# INTEGERS
x = int(1) # x will be 1
y = int(2.8) # y will be 2
z = int("3") # z will be 3

# FLOATS
x = float(1) # x will be 1.0
y = float(2.8) # y will be 2.8
z = float("3") # z will be 3.0
w = float("4.2") # w will be 4.2

# STRINGS
x = str("s1") # x will be 's1'
y = str(2) # y will be '2'
z = str(3.0) # z will be '3.0'