# PYTHON - SLICING STRINGS

# SLICING
# YOU CAN RETURN A RANGE OF CHARACTERS BY USING THE SLICE SYNTAX.
# SPECIFY THE START INDEX AND THE END INDEX, SEPARATED BY A COLON, TO RETURN A PART OF THE STRING.
# GET THE CHARACTERS FROM POSITION 2 TO POSITION 5 (NOT INCLUDED):
b = "Hello, World!"
print(b[2:5])
# NOTE: THE FIRST CHARACTER HAS INDEX 0.

# SLICE FROM THE START
# BY LEAVING OUT THE START INDEX, THE RANGE WILL START AT THE FIRST CHARACTER:
b = "Hello, World!"
print(b[:5])

# SLICE TO THE END
# BY LEAVING OUT THE END INDEX, THE RANGE WILL GO TO THE END:
b = "Hello, World!"
print(b[2:])

# NEGATIVE INDEXING
# USE NEGATIVE INDEXING TO START THE SLICE FROM THE END OF THE STRING:
# GET THE CHARACTERS:
# FROM: "o" in "World!" (POSITION -5)
# TO, BUT NOT INCLUDED: "d" in "World!" (POSITION -2):
b = "Hello, World!"
print(b[-5:-2])