# PYHTON IDENTATION
# IDENTATION REFERS TO THE SPACES AT THE BEGINNING OF A CODE LINE
""" WHERE IN OTHER PROGRAMMING LANGUAGES THE INDENTATION IN CODE IS FOR READABILITY ONLY, THE 
IDENTATION IN PYTHON IS VERY IMPORTANT """
# PYTHON USES INDENTATION TO INDICATE A BLOCK OF CODE
# EXAMPLE
if 5 > 2:
    print("Five is greater than two!")

# PYTHON WILL GIVE YOU AN ERROR IF YOU SKIP THE INDENTATION
# EXAMPLE
# if 5 > 2:
# print("Five is greater than two!")

""" THE NUMBER OF SPACES IS UP TO YOU AS A PROGRAMMER, THE MOST USE IS FOUR, BUT IT
HAS TO BE AT LEAST ONE """
# EXAMPLE
if 5 > 2:
    print("Five is greater than two!")
if 5 > 2:
    print("Five is greater than two!")

""" YOU HAVE TO USE THE SAME NUMBER OF SPACES IN THE SAME BLOCK OF CODE, OTHERWISE PYTHON
WILL GIVE YOU AN ERROR """
# EXAMPLE
# if 5 > 2:
#     print("Five is greater than two!")
#       print("Five is greater than two!")

# PYTHON VARIABLES
# IN PYTHON, VARIABLES ARE CREATED WHEN YOU ASSIGN A VALUE TO IT
# EXAMPLE
x = 5
y = "Hello, World!"
# PYTHON HAS NO COMMAND FOR DECLARING A VARIABLE

