# PYTHON - ACCESS SET ITEMS

# ACCESS ITEMS
# YOU CANNOT ACCESS ITEMS IN A SET BY REFERRING TO AN INDEX OR A KEY
# BUT YOU CAN LOOP THROUGH THE SET ITEMS USING A FOR LOOP, OR ASK IF A SPECIFIED VALUE IS
# PRESENT IN A SET, BY USING THE IN KEYWORD
# EXAMPLE
# LOOP THROUGH THE SET, AND PRINT THE VALUES
thisset = {"apple", "banana", "cherry"}
for x in thisset:
    print(x)

# EXAMPLE
# CHECK IF "banana" IS PRESENT IN THE SET
thisset = {"apple", "banana", "cherry"}
print("banana" in thisset)

# CHANGE ITEMS
# ONCE A SET IS CREATED, YOU CANNOT CHANGE ITS ITEMS, BUT YOU CAN ADD NEW ITEMS