# VARIABLE NAMES
""" A VARIABLE CAN HAVE A SHORT NAME (LIKE x AND y) OR A MORE DESCRIPTIVE NAME (AGE, 
CARNAME, TOTAL_VOLUME) """
# RULES FOR PYTHON VARIABLES
# A VARIABLE NAME MUST START WITH A LETTER OR THE UNDERSCORE CHARACTER
# A VARIABLE NAME CANNOT START WITH A NUMBER
# A VARIABLE NAME CAN ONLY CONTAIN ALPHA-NUMERIC CHARACTERS AND UNDERSOCRES (A-Z, 0-9, AND _)
# VARIABLE NAMES ARE CASE-SENSITIVE (AGE, age, and Age ARE THREE DIFFERENT VARIABLES)
# A VARIABLE NAME CANNOT CONTAIN SPACES, USE CAMEL CASE INSTEAD (e.g. myVariableName)
# EXAMPLE
# LEGAL VARIABLE NAMES
myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

# ILLEGAL VARIABLE NAMES
# 2myvar = "John"
# my-var = "John"
# my var = "John"

# REMEMBER THAT VARIABLE NAMES ARE CASE-SENSITIVE

# MULTI WORDS VARIABLE NAMES
# VARIABLE NAMES WITH MORE THAN ONE WORD CAN BE DIFFICULT TO READ
# THERE ARE SEVERAL TECHNIQUES YOU CAN USE TO MAKE THEM MORE READABLE
# CAMEL CASE
# EACH WORD, EXCEPT THE FIRST, STARTS WITH A CAPITAL LETTER
myVariableName = "John"
# PASCAL CASE
# EACH WORD STARTS WITH A CAPITAL LETTER
MyVariableName = "John"
# SNAKE CASE
# EACH WORD IS SEPARATED BY AN UNDERSCORE CHARACTER
my_variable_name = "John"